sudo: required
language: java
jdk:
  - openjdk8
services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:8-jdk-alpine

script:
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install
  - ./mvnw deploy jib:build -P deploy-docker

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: nyammingsdb-api
  env: NyammingsdbApi-env
  bucket_name: elasticbeanstalk-us-east-1-127596255715
  bucket_path: nyammingsdb-api
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY